[tool.poetry]
name = "mysite"
version = "0.1.0"
description = "Django project with shop, blog and auth"
authors = ["Your Name <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "4.1.6"
django-debug-toolbar = "*"
djangorestframework = "*"
django-filter = "*"
Pillow = "*"
gunicorn = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"